name = "Boner"
author = "Ryn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e28b802e65210b978293895d1be73d1338bb8880b9c2797038c3778324a9124b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["1.20.5", "1.20.6", "1.21"]
