name = "Boner"
author = "Ryn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb7fab2f1e09244868bf8e089153b4470cd29ac11a401319a4cda6af3e449301"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["1.20.5", "1.20.6", "1.21"]
