name = "Boner"
author = "Ryn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46599fe2f0376f30cf6492b625dfbe618953d6993282ea6f4d77b51e66f7bb34"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["1.20.5", "1.20.6", "1.21"]
